platform :ios, '8.0'
target 'SellerPro' do
pod 'OpenUDID'
pod 'Masonry'
pod 'MJRefresh'
pod 'SDWebImage'
pod 'AFNetworking'
pod 'HYBNetworking'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'MGSwipeTableCell'
end
